version: 2
jobs:
  build:
    working_directory: ~/protractor
    docker:
      - image: circleci/node:9.2-browsers
  # Specify service dependencies here if necessary
  # CircleCI maintains a library of pre-built images
  # documented at https://circleci.com/docs/2.0/circleci-images/
  # - image: circleci/mongo:3.4.4

    steps:
      - checkout
      - restore_cache:
          keys: 
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: 
          name: Install local dependencies
          command: npm install
      - save_cache: 
          key: v1-dependencies-{{ checksum "package.json" }}
          paths: 
            - node_modules
      - run:
          name: Run e2e tests
          command:  |
            npm run tsc
            ./node_modules/protractor/bin/protractor protractor.conf.js
      - store_test_results:
          path : ~/protractor/Reports/e2e
      - save_cache:
          key: dependency-cache--{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - store_artifacts:
          path: ~/protractor/Reports

